[package]
name = "termulus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
eframe = "0.25.0"
egui = "0.25.0"
tokio = { version = "1.36.0", features = ["fs", "full"] }

[dependencies.nix]
version = "0.27.1"
default-features = false
features = ["process", "term", "fs"]
